### ISSUE TITLE
Some comments on your DG based on my reading

### ISSUE THREAD

**Issue by okkhoy** [AY2021S1-CS2113T-T09-2/tp#147]
- [x] Are you showing multiple associations unintentionally? (appears in multiple places. please fix all)
![image](https://user-images.githubusercontent.com/1023494/97591142-44d27280-1a3a-11eb-9703-a5887cd95166.png)
![image](https://user-images.githubusercontent.com/1023494/97591225-5d428d00-1a3a-11eb-8ff5-0509ec563212.png)

- [x] Need more info in the diagram?
![image](https://user-images.githubusercontent.com/1023494/97591894-0a1d0a00-1a3b-11eb-84bb-f6cf604f3f10.png)

- [x] (Nitpick) Possibly format using code formatting (back ticks: e.g., \` Parser\`)
![image](https://user-images.githubusercontent.com/1023494/97592157-4fd9d280-1a3b-11eb-8318-b8a18cb897c6.png)

- [x] Notation error 
![image](https://user-images.githubusercontent.com/1023494/97592384-8d3e6000-1a3b-11eb-80ba-69277cbf509a.png)

- [x] Possibly a notation error here
![image](https://user-images.githubusercontent.com/1023494/97592539-b9f27780-1a3b-11eb-96f8-676bb690898d.png)

- [x] Your sequence diagrams are quite complex. See if you can simplify most of them

- [x] You seem to have organized the DG as section full of class diagrams followed by section full of sequence diagrams. Try to use them in conjunction and explain the features if possible.

 - [x] Can possibly use reference frames to simplify your SD
![image](https://user-images.githubusercontent.com/1023494/97593020-3be2a080-1a3c-11eb-9d3c-f575614ef805.png)

- [x] More scope for simplification
![image](https://user-images.githubusercontent.com/1023494/97593202-69c7e500-1a3c-11eb-8d89-4dca07fc1e54.png)

- [x] Notation error? (Appears multiple places, please fix them)
![image](https://user-images.githubusercontent.com/1023494/97593403-a1cf2800-1a3c-11eb-92ef-1da58e8043bc.png)

- [x] Notation error
![image](https://user-images.githubusercontent.com/1023494/97593589-cc20e580-1a3c-11eb-8cf1-79f8e80eb283.png)

- [x] Notation error and possibly a logic error (?)
![image](https://user-images.githubusercontent.com/1023494/97594020-333e9a00-1a3d-11eb-9911-16e9a4e069a5.png)

- [x] This could be a SD on its own. Not sure why you put this along with the parser. An impatient reader may think your parser is also involved in executing the command. (Same thing for the next SD as well involving list command parser, and CAP . . .)
![image](https://user-images.githubusercontent.com/1023494/97594205-63863880-1a3d-11eb-8bd2-cb05e58d20b0.png)

- [x] Timetable doesn't have any UML diagrams associated. Not that it is mandatory, but it may feel left out 😞 😜 

- [x] Stray text?
![image](https://user-images.githubusercontent.com/1023494/97594657-db546300-1a3d-11eb-93ba-ab3c7069739b.png)

- [x] please ensure your manual testing instructions are error free.

**Comment by Aseanseen** [comment]
Reopen for the team's amends

**Comment by SimJunYou** [comment]
All addressed, thanks Prof
