### ISSUE TITLE
Empty Json file produces nullpointer exception

### ISSUE THREAD

**Issue by 1-Karthigeyan-1** [AY2021S1-CS2113T-T09-2/tp#284]
In this error, I left timetable_data.json file empty as shown below.
![image](https://user-images.githubusercontent.com/50498839/98512048-9d0e3d80-22a0-11eb-9c81-205b4b952848.png)

Running the ravi jar gives me this error.
![image](https://user-images.githubusercontent.com/50498839/98511950-7e0fab80-22a0-11eb-815e-7d2ecf6523a1.png)

**Comment by Aseanseen** [comment]
To add on,

![photo_2020-11-09_16-30-50](https://user-images.githubusercontent.com/45010376/98517513-fda17880-22a8-11eb-8501-2dd87a9bf206.jpg)

**Comment by SimJunYou** [comment]
:-)
