### ISSUE TITLE
Help command and error messages not updated

### ISSUE THREAD

**Issue by SimJunYou** [AY2021S1-CS2113T-T09-2/tp#60]
Latest master's `help` command shows the exit command as `exit` instead of `bye`.

Also, when an edit command (`edit -m xxx`) is entered, it gives the following result:
`Please check to make sure to follow the command format as such:
edm <module code> -m <new module code>`

**Comment by tobiasceg** [comment]
got it, fixed help command in my latest PR . 

The edit command is fixed with wang qins latest PR
